In [2]:
import numpy as np

In [13]:
l =  [ 1,2,3,4,5]
array_list = np.array(object = list_)

In [21]:
print('Type of list_ is :',type(list_))
print('Type of array_list is :',type(array_list))

Type of list_ is : <class 'list'>
Type of array_list is : <class 'numpy.ndarray'>


In [22]:
for i in list_:
    print(f'element value:{i}, datatype = {type(i)}')

element value:1, datatype = <class 'int'>
element value:2, datatype = <class 'int'>
element value:3, datatype = <class 'int'>
element value:4, datatype = <class 'int'>
element value:5, datatype = <class 'int'>


In [24]:
for i in array_list:
    print(f'element value:{i},datatype={type(i)}')

element value:1,datatype=<class 'numpy.int64'>
element value:2,datatype=<class 'numpy.int64'>
element value:3,datatype=<class 'numpy.int64'>
element value:4,datatype=<class 'numpy.int64'>
element value:5,datatype=<class 'numpy.int64'>


In [25]:
array_list=np.array(object=list_,dtype=int)

In [26]:
array_list

array([1, 2, 3, 4, 5])

In [27]:
for i in list_:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'int'>
Element value : 2, datatype = <class 'int'>
Element value : 3, datatype = <class 'int'>
Element value : 4, datatype = <class 'int'>
Element value : 5, datatype = <class 'int'>


In [28]:
for i in array_list:
    print(f'Element value : {i}, datatype = {type(i)}')

Element value : 1, datatype = <class 'numpy.int64'>
Element value : 2, datatype = <class 'numpy.int64'>
Element value : 3, datatype = <class 'numpy.int64'>
Element value : 4, datatype = <class 'numpy.int64'>
Element value : 5, datatype = <class 'numpy.int64'>


In [29]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [30]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
num_array.shape

(2, 3)

In [34]:
num_array.size

6

In [35]:
arr5=np.zeros((3,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
print(f'Size of arr5 is {arr5.size}')
print(f'Shape of arr5 is {arr5.shape}')

Size of arr5 is 9
Shape of arr5 is (3, 3)


In [ ]:
Question 6: Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]